export const catalog = [
	{
		id: '1',
		imgWebp: './images/pamatniki/1.webp',
		imgJpg: './images/pamatniki/1.jpg',
		article: '',
		title: '',
		descr: '',
		price: 0,
		pixel: '/images/1x1.png',
	},
	{
		id: '2',
		imgWebp: './images/pamatniki/2.webp',
		imgJpg: './images/pamatniki/2.jpg',
		article: '',
		title: '',
		descr: '',
		price: 0,
		pixel: '/images/1x1.png',
	},
	{
		id: '3',
		imgWebp: './images/pamatniki/3.webp',
		imgJpg: './images/pamatniki/3.jpg',
		article: '',
		title: '',
		descr: '',
		price: 0,
		pixel: '/images/1x1.png',
	},
	{
		id: '4',
		imgWebp: './images/pamatniki/4.webp',
		imgJpg: './images/pamatniki/4.jpg',
		article: '',
		title: '',
		descr: '',
		price: 0,
		pixel: '/images/1x1.png',
	},
]
