export const catalog = [
	{
		id: '1',
		imgWebp: './images/graver/1.webp',
		imgJpg: './images/graver/1.jpg',
		article: '',
		title: '',
		descr: '',
		price: 0,
		pixel: '/images/1x1.png',
	},
	{
		id: '2',
		imgWebp: './images/graver/2.webp',
		imgJpg: './images/graver/2.jpg',
		article: '',
		title: '',
		descr: '',
		price: 0,
		pixel: '/images/1x1.png',
	},
	{
		id: '3',
		imgWebp: './images/graver/3.webp',
		imgJpg: './images/graver/3.jpg',
		article: '',
		title: '',
		descr: '',
		price: 0,
		pixel: '/images/1x1.png',
	},
	{
		id: '4',
		imgWebp: './images/graver/4.webp',
		imgJpg: './images/graver/4.jpg',
		article: '',
		title: '',
		descr: '',
		price: 0,
		pixel: '/images/1x1.png',
	},
	{
		id: '5',
		imgWebp: './images/graver/5.webp',
		imgJpg: './images/graver/5.jpg',
		article: '',
		title: '',
		descr: '',
		price: 0,
		pixel: '/images/1x1.png',
	},
	{
		id: '6',
		imgWebp: './images/graver/6.webp',
		imgJpg: './images/graver/6.jpg',
		article: '',
		title: '',
		descr: '',
		price: 0,
		pixel: '/images/1x1.png',
	},
	{
		id: '7',
		imgWebp: './images/graver/7.webp',
		imgJpg: './images/graver/7.jpg',
		article: '',
		title: '',
		descr: '',
		price: 0,
		pixel: '/images/1x1.png',
	},
]
