const catalog = [
	{
		id: '7',
		imgWebp: '/images/grobs/bergamo-dark-nuts.webp',
		imgJpg: '/images/grobs/bergamo-dark-nuts.jpg',
		article: 'Артикул: ФБ',
		title: 'Бергамо цвет тёмный орех',
		descr: 'Шестигранный, лаковое покрытие Материал изготовления: гроб ...',
		price: 24000,
		pixel: './images/1x1.png',
		type: 'polirovan',
	},
	{
		id: '8',
		imgWebp: '/images/grobs/bergamo-light-nuts.webp',
		imgJpg: '/images/grobs/bergamo-light-nuts.jpg',
		article: 'Артикул: ФБ',
		title: 'Бергамо цвет светлый орех',
		descr: 'Шестигранный, лаковое покрытие Материал изготовления: гроб ...',
		price: 24000,
		pixel: './images/1x1.png',
		type: 'polirovan',
	},
	{
		id: '9',
		imgWebp: '/images/grobs/pechal.webp',
		imgJpg: '/images/grobs/pechal.jpg',
		article: 'Артикул: ФСР-6',
		title: 'Гроб Печаль',
		descr: 'Шестигранный,гроб изготовлен из массива сосны. Форма ...',
		price: 16500,
		pixel: './images/1x1.png',
		type: 'polirovan',
	},
	{
		id: '10',
		imgWebp: '/images/grobs/versace.webp',
		imgJpg: '/images/grobs/versace.jpg',
		article: 'Артикул: ФСР-6',
		title: 'Гроб Версаче',
		descr: 'Шестигранный Материал изготовления: гроб изготовлен из ...',
		price: 27000,
		pixel: './images/1x1.png',
		type: 'polirovan',
		type2: 'elite',
	},
	{
		id: '11',
		imgWebp: '/images/grobs/iris-light-nuts.webp',
		imgJpg: '/images/grobs/iris-light-nuts.jpg',
		article: 'Артикул: ФИЭ-6С',
		title: 'Ирис светлый орех',
		descr: 'Шестигранный,Лаковое покрытие, Фурнитура: Ручки (материал: ...',
		price: 18000,
		pixel: './images/1x1.png',
		type: 'polirovan',
	},
	{
		id: '12',
		imgWebp: '/images/grobs/loredo.webp',
		imgJpg: '/images/grobs/loredo.jpg',
		article: '',
		title: 'Гроб Лоредо',
		descr: 'Шестигранный,гроб изготовлен из массива сосны. Форма: ...',
		price: 27000,
		pixel: './images/1x1.png',
		type: 'polirovan',
	},
	{
		id: '13',
		imgWebp: '/images/grobs/koloda.webp',
		imgJpg: '/images/grobs/koloda.jpg',
		article: 'Артикул: Б-4',
		title: 'Колода',
		descr: 'Изготовлен из ДСП облицованный натуральным шпоном. ...',
		price: 17500,
		pixel: './images/1x1.png',
		type: 'polirovan',
		type2: 'elite',
	},
	{
		id: '14',
		imgWebp: '/images/grobs/vegas-white.webp',
		imgJpg: '/images/grobs/vegas-white.jpg',
		article: 'Артикул: ФБА-2Б',
		title: 'Вегас цвет белый',
		descr: 'Двухкрышечный, четырёхгранный, изготовлен из массива сосны ...',
		price: 60000,
		pixel: './images/1x1.png',
		type: 'polirovan',
		type2: 'elite',
	},
	{
		id: '15',
		imgWebp: '/images/grobs/vegas-maxagon.webp',
		imgJpg: '/images/grobs/vegas-maxagon.jpg',
		article: 'Артикул: ФБА-2Б',
		title: 'Вегас цвет махагон',
		descr: 'Двухкрышечный, четырёхгранный, изготовлен из массива сосны ...',
		price: 60000,
		pixel: './images/1x1.png',
		type: 'polirovan',
		type2: 'elite',
	},
	{
		id: '16',
		imgWebp: '/images/grobs/iris-dark-nuts.webp',
		imgJpg: '/images/grobs/iris-dark-nuts.jpg',
		article: 'Артикул: ФИЭ-6Т',
		title: 'Ирис темный орех',
		descr: 'Шестигранный, лаковое покрытие Материал изготовления: гроб ...',
		price: 18000,
		pixel: './images/1x1.png',
		type: 'polirovan',
	},
	{
		id: '17',
		imgWebp: '/images/grobs/sirius-white.webp',
		imgJpg: '/images/grobs/sirius-white.jpg',
		article: 'Артикул: ФСИ-6',
		title: 'Сириус цвет Белый',
		descr: 'Шестигранный,Цвет изделия: белый, лаковое ...',
		price: 20000,
		pixel: './images/1x1.png',
		type: 'polirovan',
	},
	{
		id: '18',
		imgWebp: '/images/grobs/sirius-nuts.webp',
		imgJpg: '/images/grobs/sirius-nuts.jpg',
		article: 'Артикул: ФСИ-6',
		title: 'Сириус цвет Орех',
		descr: 'Шестигранный,Цвет изделия: орех - с темными гранями, ...',
		price: 20000,
		pixel: './images/1x1.png',
		type: 'polirovan',
	},

	{
		id: '1',
		imgWebp: './images/grobs/t-2.webp',
		imgJpg: './images/grobs/t-2.jpg',
		article: 'Артикул: Тип 2',
		title: 'Гроб Т-2',
		descr: 'Цвет ткани гроба: красный',
		price: 3000,
		pixel: '/images/1x1.png',
		type: 'derevo',
	},
	{
		id: '2',
		imgWebp: '/images/grobs/t-2p.webp',
		imgJpg: '/images/grobs/t-2p.jpg',
		article: 'Артикул: Тип 2 П',
		title: 'Гроб Т 2П',
		descr: 'Цвет ткани гроба: красный',
		price: 3300,
		pixel: './images/1x1.png',
		type: 'derevo',
	},
	{
		id: '1',
		imgWebp: '/images/grobs/6.1.webp',
		imgJpg: '/images/grobs/6.1.webp',
		article: 'Артикул: Тип 6/1',
		title: 'Гроб Т 6/1',
		descr: '',
		price: 6000,
		pixel: './images/1x1.png',
		type: 'derevo',
	},
	{
		id: '3',
		imgWebp: '/images/grobs/t-19.webp',
		imgJpg: '/images/grobs/t-19.jpg',
		article: 'Артикул: Тип 19',
		title: 'Гроб Т-19',
		descr: 'Цвет ткани гроба: красный, бордовый, черный',
		price: 5900,
		pixel: './images/1x1.png',
		type: 'derevo',
	},
	{
		id: '4',
		imgWebp: '/images/grobs/t-4-p.webp',
		imgJpg: '/images/grobs/t-4-p.jpg',
		article: 'Артикул: Тип 4 П',
		title: 'Гроб Т-4 П',
		descr: 'Цвет ткани гроба: красный, синий, зеленый, фиолетовый, серый',
		price: 4600,
		pixel: './images/1x1.png',
		type: 'derevo',
	},
	{
		id: '5',
		imgWebp: '/images/grobs/t-24.webp',
		imgJpg: '/images/grobs/t-24.jpg',
		article: 'Артикул: Тип 24',
		title: 'Гроб Т-24',
		descr: 'Высота корзины 90 см.',
		price: 6000,
		pixel: './images/1x1.png',
		type: 'derevo',
	},
	{
		id: '6',
		imgWebp: '/images/grobs/t-7-p.webp',
		imgJpg: '/images/grobs/t-7-p.jpg',
		article: 'Артикул: Тип 7П',
		title: 'Гроб Т-7П',
		descr: 'Высота корзины 90 см.',
		price: 4900,
		pixel: './images/1x1.png',
		type: 'derevo',
	},
]

export { catalog }
