const catalog = [
  {
    id: "1",
    imgWebp: "./images/venki/t-325.webp",
    imgJpg: "./images/venki/t-325.jpg",
    article: "Артикул: Тип 325 В",
    title: "Венок Т 325.",
    descr: "Высота 130 см.",
    price: 2300,
    pixel: "/images/1x1.png",
  },
  {
    id: "2",
    imgWebp: "./images/venki/t-324.webp",
    imgJpg: "./images/venki/t-324.jpg",
    article: "Артикул: Тип 324 В",
    title: "Венок Т 324",
    descr: "Высота 115 см.",
    price: 2200,
    pixel: "/images/1x1.png",
  },
  {
    id: "3",
    imgWebp: "./images/venki/t-323.webp",
    imgJpg: "./images/venki/t-323.jpg",
    article: "Артикул: Тип 323 В",
    title: "Венок Т 323",
    descr: "Высота 130 см.",
    price: 4150,
    pixel: "/images/1x1.png",
  },
  // {
  //   id: "4",
  //   imgWebp: "./images/venki/t-322.webp",
  //   imgJpg: "./images/venki/t-322.jpg",
  //   article: "Артикул: Тип 322 В",
  //   title: "Венок Т 322",
  //   descr: "Высота 175 см",
  //   price: 6700,
  //   pixel: "/images/1x1.png",
  // },
  // {
  //   id: "5",
  //   imgWebp: "./images/venki/t-321.webp",
  //   imgJpg: "./images/venki/t-321.jpg",
  //   article: "Артикул: Тип 321",
  //   title: "Венок Т 321",
  //   descr: "Высота 120 см.",
  //   price: 1150,
  //   pixel: "/images/1x1.png",
  // },
  // {
  //   id: "6",
  //   imgWebp: "./images/venki/t-319.webp",
  //   imgJpg: "./images/venki/t-319.jpg",
  //   article: "Артикул: Тип 319 В",
  //   title: "Венок Т 319",
  //   descr: "Высота 110 см.",
  //   price: 1080,
  //   pixel: "/images/1x1.png",
  // },
  {
    id: "7",
    imgWebp: "./images/venki/t-317.webp",
    imgJpg: "./images/venki/t-317.jpg",
    article: "Артикул: Тип 317 В",
    title: "Венок Т 317",
    descr: "Высота 145 см.",
    price: 3750,
    pixel: "/images/1x1.png",
  },
  {
    id: "8",
    imgWebp: "./images/venki/t-315.webp",
    imgJpg: "./images/venki/t-315.jpg",
    article: "Артикул: Тип 315 В",
    title: "Венок Т 315",
    descr: "Высота 115 см",
    price: 2250,
    pixel: "/images/1x1.png",
  },
  {
    id: "9",
    imgWebp: "./images/venki/t-313.webp",
    imgJpg: "./images/venki/t-313.jpg",
    article: "Артикул: Тип 313 В",
    title: "Венок Т 313",
    descr: "Высота 145 см",
    price: 1700,
    pixel: "/images/1x1.png",
  },
  {
    id: "10",
    imgWebp: "./images/venki/t-312.webp",
    imgJpg: "./images/venki/t-312.jpg",
    article: "Артикул: Тип 312 В",
    title: "Венок Т 312",
    descr: "Высота 30 см.",
    price: 320,
    pixel: "/images/1x1.png",
  },
  {
    id: "11",
    imgWebp: "./images/venki/t-308.webp",
    imgJpg: "./images/venki/t-308.jpg",
    article: "Артикул: Тип 308 В",
    title: "Венок Т 312",
    descr: "Высота 130 см.",
    price: 3680,
    pixel: "/images/1x1.png",
  },
  {
    id: "12",
    imgWebp: "./images/venki/t-307.webp",
    imgJpg: "./images/venki/t-307.jpg",
    article: "Артикул: Тип 307 В",
    title: "Венок Т 307",
    descr: "Высота 155 см.",
    price: 3450,
    pixel: "/images/1x1.png",
  },
  // {
  //   id: "13",
  //   imgWebp: "./images/venki/t-306.webp",
  //   imgJpg: "./images/venki/t-306.jpg",
  //   article: "Артикул: Тип 306 В",
  //   title: "Венок Т 306",
  //   descr: "Высота 145 см.",
  //   price: 2750,
  //   pixel: "/images/1x1.png",
  // },
  {
    id: "14",
    imgWebp: "./images/venki/t-305.webp",
    imgJpg: "./images/venki/t-305.jpg",
    article: "Артикул: Тип 305 В",
    title: "Венок Т 305",
    descr: "",
    price: 3700,
    pixel: "/images/1x1.png",
  },
  {
    id: "15",
    imgWebp: "./images/venki/t-303.webp",
    imgJpg: "./images/venki/t-303.jpg",
    article: "Артикул: Тип 303",
    title: "Венок Т 303",
    descr: "Высота 115 см.",
    price: 2400,
    pixel: "/images/1x1.png",
  },

  // {
  //   id: "18",
  //   imgWebp: "./images/venki/t-298.webp",
  //   imgJpg: "./images/venki/t-298.jpg",
  //   article: "Артикул: Тип 298 В",
  //   title: "Венок Т 298",
  //   descr: "Высота 150 см.",
  //   price: 1100,
  //   pixel: "/images/1x1.png",
  // },
  // {
  //   id: "19",
  //   imgWebp: "./images/venki/t-297.webp",
  //   imgJpg: "./images/venki/t-297.jpg",
  //   article: "Артикул: Тип 297 В",
  //   title: "Венок Т 297",
  //   descr: "Высота 85 см.",
  //   price: 500,
  //   pixel: "/images/1x1.png",
  // },
  // {
  //   id: "20",
  //   imgWebp: "./images/venki/t-298.webp",
  //   imgJpg: "./images/venki/t-298.jpg",
  //   article: "Артикул: Тип 298 В",
  //   title: "Венок Т 298",
  //   descr: "Высота 150 см.",
  //   price: 1100,
  //   pixel: "/images/1x1.png",
  // },
  {
    id: "21",
    imgWebp: "./images/venki/t-295.webp",
    imgJpg: "./images/venki/t-295.jpg",
    article: "Артикул: Тип 295",
    title: "Венок Т 295",
    descr: "Высота 110 см.",
    price: 1620,
    pixel: "/images/1x1.png",
  },
  {
    id: "22",
    imgWebp: "./images/venki/t-293.webp",
    imgJpg: "./images/venki/t-293.jpg",
    article: "Артикул: Тип 293 В",
    title: "Венок Т 293",
    descr: "Высота 145 см.",
    price: 3750,
    pixel: "/images/1x1.png",
  },
  {
    id: "23",
    imgWebp: "./images/venki/t-292.webp",
    imgJpg: "./images/venki/t-292.jpg",
    article: "Артикул: Тип 292 В",
    title: "Венок Т 292",
    descr: "Высота 175 см.",
    price: 5800,
    pixel: "/images/1x1.png",
  },
  {
    id: "24",
    imgWebp: "./images/venki/t-287.webp",
    imgJpg: "./images/venki/t-287.jpg",
    article: "Артикул: Тип 287 В",
    title: "Венок Т 287",
    descr: "",
    price: 760,
    pixel: "/images/1x1.png",
  },
  {
    id: "25",
    imgWebp: "./images/venki/t-286.webp",
    imgJpg: "./images/venki/t-286.jpg",
    article: "Артикул: Тип 286 В",
    title: "Венок Т 286",
    descr: "Высота 90 см.",
    price: 730,
    pixel: "/images/1x1.png",
  },
  {
    id: "26",
    imgWebp: "./images/venki/t-285.webp",
    imgJpg: "./images/venki/t-285.jpg",
    article: "Артикул: Тип 285 В",
    title: "Венок Т 285",
    descr: "Высота 135 см.",
    price: 1970,
    pixel: "/images/1x1.png",
  },
  // {
  //   id: "27",
  //   imgWebp: "./images/venki/t-284.webp",
  //   imgJpg: "./images/venki/t-284.jpg",
  //   article: "Артикул: Тип 284 В",
  //   title: "Венок Т 284",
  //   descr: "Высота 90 см.",
  //   price: 500,
  //   pixel: "/images/1x1.png",
  // },
  {
    id: "28",
    imgWebp: "./images/venki/t-283.webp",
    imgJpg: "./images/venki/t-283.jpg",
    article: "Артикул: Тип 283 В",
    title: "Венок Т 283",
    descr: "Высота 90 см.",
    price: 750,
    pixel: "/images/1x1.png",
  },
  {
    id: "29",
    imgWebp: "./images/venki/t-282.webp",
    imgJpg: "./images/venki/t-282.jpg",
    article: "Артикул: Тип 282 В",
    title: "Венок Т 282",
    descr: "Высота 90 см.",
    price: 620,
    pixel: "/images/1x1.png",
  },
  {
    id: "30",
    imgWebp: "./images/venki/t-281.webp",
    imgJpg: "./images/venki/t-281.jpg",
    article: "Артикул: Тип 281 В",
    title: "Венок Т 281",
    descr: "Высота 90 см.",
    price: 850,
    pixel: "/images/1x1.png",
  },
  // {
  //   id: "31",
  //   imgWebp: "./images/venki/t-281.webp",
  //   imgJpg: "./images/venki/t-281.jpg",
  //   article: "Артикул: Тип 281 В",
  //   title: "Венок Т 281",
  //   descr: "Высота 90 см.",
  //   price: 650,
  //   pixel: "/images/1x1.png",
  // },
  {
    id: "32",
    imgWebp: "./images/venki/t-277.webp",
    imgJpg: "./images/venki/t-277.jpg",
    article: "Артикул: Тип 277 В",
    title: "Венок Т 277",
    descr: "Высота 175 см.",
    price: 5100,
    pixel: "/images/1x1.png",
  },
  {
    id: "33",
    imgWebp: "./images/venki/t-9-0.webp",
    imgJpg: "./images/venki/t-9-0.jpg",
    article: "Артикул: T9-0",
    title: "Венок Т9-0",
    descr: "Высота 195 см.",
    price: 1200,
    pixel: "/images/1x1.png",
  },
  {
    id: "34",
    imgWebp: "./images/venki/t-4-k.webp",
    imgJpg: "./images/venki/t-4-k.jpg",
    article: "Артикул: 4 K",
    title: "Венок Т 4 K",
    descr: "Высота 175 см.",
    price: 1320,
    pixel: "/images/1x1.png",
  },
  {
    id: "35",
    imgWebp: "./images/venki/t-274.webp",
    imgJpg: "./images/venki/t-274.jpg",
    article: "Артикул: Тип 274 В",
    title: "Венок Т 274",
    descr: "Высота 145 см.",
    price: 3000,
    pixel: "/images/1x1.png",
  },
  {
    id: "36",
    imgWebp: "./images/venki/t-272.webp",
    imgJpg: "./images/venki/t-272.jpg",
    article: "Артикул: Тип 272 В",
    title: "Венок Т 272",
    descr: "Высота 115 см.",
    price: 1800,
    pixel: "/images/1x1.png",
  },
  {
    id: "37",
    imgWebp: "./images/venki/t-269.webp",
    imgJpg: "./images/venki/t-269.jpg",
    article: "Артикул: Тип 269 В",
    title: "Венок Т 269",
    descr: "Высота 105 см.",
    price: 1800,
    pixel: "/images/1x1.png",
  },
  {
    id: "38",
    imgWebp: "./images/venki/t-263.webp",
    imgJpg: "./images/venki/t-263.jpg",
    article: "Артикул: Тип 263",
    title: "Венок Т 263",
    descr: "Высота 145 см.",
    price: 3680,
    pixel: "/images/1x1.png",
  },
  {
    id: "39",
    imgWebp: "./images/venki/t-242.webp",
    imgJpg: "./images/venki/t-242.jpg",
    article: "Артикул: Тип 242",
    title: "Венок Т 242",
    descr: "Высота 120 см.",
    price: 1850,
    pixel: "/images/1x1.png",
  },
  {
    id: "40",
    imgWebp: "./images/venki/t-242-red.webp",
    imgJpg: "./images/venki/t-242-red.jpg",
    article: "Артикул: Тип 242 к",
    title: "Венок Т 242 к",
    descr: "Высота 120 см.",
    price: 1850,
    pixel: "/images/1x1.png",
  },
  // {
  //   id: "40",
  //   imgWebp: "./images/venki/t-237.webp",
  //   imgJpg: "./images/venki/t-237.jpg",
  //   article: "Артикул: Тип 237",
  //   title: "Венок Т 237",
  //   descr: "Высота 110 см.",
  //   price: 700,
  //   pixel: "/images/1x1.png",
  // },
  // {
  //   id: "41",
  //   imgWebp: "./images/venki/t-231.webp",
  //   imgJpg: "./images/venki/t-231.jpg",
  //   article: "Артикул: Тип 231",
  //   title: "Венок Т 231",
  //   descr: "Высота 105 см.",
  //   price: 1470,
  //   pixel: "/images/1x1.png",
  // },
];
export {catalog};